install.packages("ggiraphExtra")
install.packages("maps")
install.packages("ggplot2")
install.packages("mapproj")
library(ggiraphExtra)
str(USArrests)
head(USArrests)
library(tibble)
crime <- rownames_to_column(USArrests, var = "state")
crime$state <- tolower(crime$state)
str(crime)
library(ggplot2)
library(ggplot)
library(maps)

library(mapproj) 
states_map <- map_data("state")
str(states_map)
ggChoropleth(data = crime ,aes(fill = Murder, map_id = state), map = states_map)
# ggChoropleth(data = crime ,aes(fill = Murder, map_id = state), map = states_map,interactive =T)