library(KoNLP)
library(dplyr)
useSejongDic()
twit<- read.csv("twitter.csv",header =T,stringsAsFactors =F,fileEncoding = "UTF-8")
twit <- rename(twit, no= 번호, id = 계정이름, date = 작성일, tw =내용)
library(stringr)
twit$tw <- str_replace_all(twit$tw, "\\W", " ")
nouns <- extractNoun(twit$tw)
wordcount <- table(unlist(nouns))
df_word <-as.data.frame(wordcount, stringsAsFactors =F)
df_word <- rename(df_word, word =Var1, freq= Freq)
df_word <- filter(df_word, nchar(word) >=2)
top20 <-df_word %>% arrange(desc(freq)) %>% head(20)
top20
install.packages("wordcloud")
library(wordcloud, help, pos = 2, lib.loc = NULL)
pal <- brewer.pal(8,"Dark2")
set.seed(1234)
wordcloud(words =df_word$word,freq =df_word$freq,min.freq =10,
max.words=200,random.order =F,rot.per=.1,scale =c(6,0.2),colors =pal)
